require("xfdm.base")

xfdm:requestConnector("cmd_ap_disc",         xfdmLinkCommand, "sim/autopilot/servos_off_any")
xfdm:requestConnector("cmd_pitch_trim_down", xfdmLinkCommand, "sim/flight_controls/pitch_trim_down")
xfdm:requestConnector("cmd_pitch_trim_up",   xfdmLinkCommand, "sim/flight_controls/pitch_trim_up")

xfdm:requestConnector("axis_pitch",                   xfdmLinkAxis, "Pitch")
xfdm:requestConnector("axis_roll",                    xfdmLinkAxis, "Roll")
xfdm:requestConnector("axis_yaw",                     xfdmLinkAxis, "Yaw")
xfdm:requestConnector("axis_throttle",                xfdmLinkAxis, "Throttle")
xfdm:requestConnector("axis_collective",              xfdmLinkAxis, "Collective")
xfdm:requestConnector("axis_left_toe_brake",          xfdmLinkAxis, "Left toe brake")
xfdm:requestConnector("axis_right_toe_brake",         xfdmLinkAxis, "Right toe brake")
xfdm:requestConnector("axis_prop",                    xfdmLinkAxis, "Prop")
xfdm:requestConnector("axis_mixture",                 xfdmLinkAxis, "Mixture")
xfdm:requestConnector("axis_carb_heat",               xfdmLinkAxis, "Carb heat")
xfdm:requestConnector("axis_flaps",                   xfdmLinkAxis, "Flaps")
xfdm:requestConnector("axis_thrust_vector",           xfdmLinkAxis, "Thrust vector")
xfdm:requestConnector("axis_wing_sweep",              xfdmLinkAxis, "Wing sweep")
xfdm:requestConnector("axis_speedbrakes",             xfdmLinkAxis, "Speedbrakes")
xfdm:requestConnector("axis_displacement",            xfdmLinkAxis, "Displacement")
xfdm:requestConnector("axis_reverse",                 xfdmLinkAxis, "Reverse")
xfdm:requestConnector("axis_elevator_trim",           xfdmLinkAxis, "Elevator trim")
xfdm:requestConnector("axis_aileron_trim",            xfdmLinkAxis, "Aileron trim")
xfdm:requestConnector("axis_rudder_trim",             xfdmLinkAxis, "Rudder trim")
xfdm:requestConnector("axis_throttle_1",              xfdmLinkAxis, "Throttle 1")
xfdm:requestConnector("axis_throttle_2",              xfdmLinkAxis, "Throttle 2")
xfdm:requestConnector("axis_throttle_3",              xfdmLinkAxis, "Throttle 3")
xfdm:requestConnector("axis_throttle_4",              xfdmLinkAxis, "Throttle 4")
xfdm:requestConnector("axis_prop_1",                  xfdmLinkAxis, "Prop 1")
xfdm:requestConnector("axis_prop_2",                  xfdmLinkAxis, "Prop 2")
xfdm:requestConnector("axis_prop_3",                  xfdmLinkAxis, "Prop 3")
xfdm:requestConnector("axis_prop_4",                  xfdmLinkAxis, "Prop 4")
xfdm:requestConnector("axis_mixture_1",               xfdmLinkAxis, "Mixture 1")
xfdm:requestConnector("axis_mixture_2",               xfdmLinkAxis, "Mixture 2")
xfdm:requestConnector("axis_mixture_3",               xfdmLinkAxis, "Mixture 3")
xfdm:requestConnector("axis_mixture_4",               xfdmLinkAxis, "Mixture 4")
xfdm:requestConnector("axis_reverse_1",               xfdmLinkAxis, "Reverse 1")
xfdm:requestConnector("axis_reverse_2",               xfdmLinkAxis, "Reverse 2")
xfdm:requestConnector("axis_reverse_3",               xfdmLinkAxis, "Reverse 3")
xfdm:requestConnector("axis_reverse_4",               xfdmLinkAxis, "Reverse 4")
xfdm:requestConnector("axis_landing_gear",            xfdmLinkAxis, "Landing gear")
xfdm:requestConnector("axis_nosewheel_tiller",        xfdmLinkAxis, "Nosewheel tiller")
xfdm:requestConnector("axis_backup_throttle",         xfdmLinkAxis, "Backup throttle")
xfdm:requestConnector("axis_auto_roll",               xfdmLinkAxis, "Auto roll")
xfdm:requestConnector("axis_auto_pitch",              xfdmLinkAxis, "Auto pitch")
xfdm:requestConnector("axis_cowl_flaps",              xfdmLinkAxis, "Cowl flaps")
xfdm:requestConnector("axis_view_left_right",         xfdmLinkAxis, "View left/right")
xfdm:requestConnector("axis_view_up_down",            xfdmLinkAxis, "View up/down")
xfdm:requestConnector("axis_view_zoom",               xfdmLinkAxis, "View zoom")
xfdm:requestConnector("axis_camera_left_right",       xfdmLinkAxis, "Camera left/right")
xfdm:requestConnector("axis_camera_up_down",          xfdmLinkAxis, "Camera up/down")
xfdm:requestConnector("axis_camera_zoom",             xfdmLinkAxis, "Camera zoom")
xfdm:requestConnector("axis_gun_bomb_left_right",     xfdmLinkAxis, "Gun/bomb left/right")
xfdm:requestConnector("axis_gun_bomb_up_down",        xfdmLinkAxis, "Gun/bomb up/down")
xfdm:requestConnector("axis_vr_touchpad_x",           xfdmLinkAxis, "VR Touchpad X")
xfdm:requestConnector("axis_vr_touchpad_y",           xfdmLinkAxis, "VR Touchpad Y")
xfdm:requestConnector("axis_vr_trigger",              xfdmLinkAxis, "VR Trigger")
xfdm:requestConnector("axis_custom_command",          xfdmLinkAxis, "Custom command(s)")
xfdm:requestConnector("axis_throttle_5",              xfdmLinkAxis, "Throttle 5")
xfdm:requestConnector("axis_throttle_6",              xfdmLinkAxis, "Throttle 6")
xfdm:requestConnector("axis_throttle_7",              xfdmLinkAxis, "Throttle 7")
xfdm:requestConnector("axis_throttle_8",              xfdmLinkAxis, "Throttle 8")
xfdm:requestConnector("axis_cowl_flaps_1",            xfdmLinkAxis, "Cowl flaps 1")
xfdm:requestConnector("axis_cowl_flaps_2",            xfdmLinkAxis, "Cowl flaps 2")
xfdm:requestConnector("axis_cowl_flaps_3",            xfdmLinkAxis, "Cowl flaps 3")
xfdm:requestConnector("axis_cowl_flaps_4",            xfdmLinkAxis, "Cowl flaps 4")
xfdm:requestConnector("axis_cowl_flaps_5",            xfdmLinkAxis, "Cowl flaps 5")
xfdm:requestConnector("axis_cowl_flaps_6",            xfdmLinkAxis, "Cowl flaps 6")
xfdm:requestConnector("axis_cowl_flaps_7",            xfdmLinkAxis, "Cowl flaps 7")
xfdm:requestConnector("axis_cowl_flaps_8",            xfdmLinkAxis, "Cowl flaps 8")
xfdm:requestConnector("axis_throttle_vertical",       xfdmLinkAxis, "Throttle Vertical")
xfdm:requestConnector("axis_throttle_horizontal",     xfdmLinkAxis, "Throttle Horizontal")
xfdm:requestConnector("axis_copilot_pitch",           xfdmLinkAxis, "Copilot Pitch")
xfdm:requestConnector("axis_copilot_roll",            xfdmLinkAxis, "Copilot Roll")
xfdm:requestConnector("axis_copilot_yaw",             xfdmLinkAxis, "Copilot Yaw")
xfdm:requestConnector("axis_copilot_left_toe_brake",  xfdmLinkAxis, "Copilot Left toe brake")
xfdm:requestConnector("axis_copilot_right_toe_brake", xfdmLinkAxis, "Copilot Right toe brake")
